"""add card usd price

Revision ID: 07540dd09593
Revises: e12c975172e1
Create Date: 2026-06-02 20:45:19.070544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07540dd09593'
down_revision: Union[str, Sequence[str], None] = 'e12c975172e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('usd_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'usd_price')
    # ### end Alembic commands ###
