"""add foil quantity

Revision ID: 5bd381524faa
Revises: 07540dd09593
Create Date: 2026-06-04 19:19:31.073739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd381524faa'
down_revision: Union[str, Sequence[str], None] = '07540dd09593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_cards', sa.Column('foil_quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_cards', 'foil_quantity')
    # ### end Alembic commands ###
