"""add set fields to cards

Revision ID: 5ca1faf04521
Revises: 225bafa7aad5
Create Date: 2026-05-19 11:37:51.467118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ca1faf04521'
down_revision: Union[str, Sequence[str], None] = '225bafa7aad5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('set_name', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('set_code', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('collector_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'collector_number')
    op.drop_column('cards', 'set_code')
    op.drop_column('cards', 'set_name')
    # ### end Alembic commands ###
