"""add commander flag to collection cards

Revision ID: 613574b548a0
Revises: d75f45ba7809
Create Date: 2026-05-22 01:09:20.337811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '613574b548a0'
down_revision: Union[str, Sequence[str], None] = 'd75f45ba7809'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_cards', sa.Column('is_commander', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_cards', 'is_commander')
    # ### end Alembic commands ###
