"""add color fields to cards

Revision ID: 8c1aedc682cf
Revises: cfe8760c1f94
Create Date: 2026-05-21 15:36:51.034563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c1aedc682cf'
down_revision: Union[str, Sequence[str], None] = 'cfe8760c1f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('colors', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('color_identity', sa.String(), nullable=True))
    op.add_column('cards', sa.Column('cmc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'cmc')
    op.drop_column('cards', 'color_identity')
    op.drop_column('cards', 'colors')
    # ### end Alembic commands ###
