"""add foil price to cards

Revision ID: ba8044c4e7ab
Revises: 5bd381524faa
Create Date: 2026-06-06 20:42:36.796176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8044c4e7ab'
down_revision: Union[str, Sequence[str], None] = '5bd381524faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('usd_foil_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'usd_foil_price')
    # ### end Alembic commands ###
