"""add set_code to collections

Revision ID: cfe8760c1f94
Revises: 5ca1faf04521
Create Date: 2026-05-20 09:41:54.069977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe8760c1f94'
down_revision: Union[str, Sequence[str], None] = '5ca1faf04521'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('set_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'set_code')
    # ### end Alembic commands ###
