"""add deck format to collections

Revision ID: d75f45ba7809
Revises: 44c0dcdcb212
Create Date: 2026-05-21 21:13:06.668255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75f45ba7809'
down_revision: Union[str, Sequence[str], None] = '44c0dcdcb212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('deck_format', sa.Enum('COMMANDER', 'STANDARD', 'MODERN', 'PAUPER', name='deckformat'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'deck_format')
    # ### end Alembic commands ###
