"""add cascade delete to collections

Revision ID: e12c975172e1
Revises: 613574b548a0
Create Date: 2026-05-27 20:14:08.291575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e12c975172e1'
down_revision: Union[str, Sequence[str], None] = '613574b548a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collection_cards_collection_id_fkey'), 'collection_cards', type_='foreignkey')
    op.create_foreign_key(None, 'collection_cards', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collection_cards', type_='foreignkey')
    op.create_foreign_key(op.f('collection_cards_collection_id_fkey'), 'collection_cards', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###
